### ISSUE TITLE
Error running one single cell image

### ISSUE THREAD

**Issue by MehrsaMehrabi** [Cardiovascular-Modeling-Laboratory/zlineDetection#40]
Undefined function 'contains' for input arguments of type 'char'.

Error in singleCellSummarypdf (line 128)
        if contains(im_struct.im_name,'AR')

Error in runDirectory (line 277)
            singleCellSummarypdf(im_struct, settings, oop_struct);

Error in runMultipleCoverSlips (line 74)
        runDirectory( settings, zline_path{k,1}, zline_images{k,1},...

Error in RUNzlineDetection (line 245)
    runMultipleCoverSlips(settings, zline_images, zline_path, name_CS, ...

Error in zlineDetection>RUN_Callback (line 333)
RUNzlineDetection(handles);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in zlineDetection (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)zlineDetection('RUN_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating DestroyedObject Callback

**Comment by tessamorris** [comment]
This is actually an issue with the Matlab version. I have created an independent, more descriptive issue.
